config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/talentos'
  get 'home/depoimentos'

  root 'home#index'

  resources :students
  resources :courses
  resources :briefs
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @students = Student.all
    @briefs = Brief.all
    @courses = Course.all
  end

  def talentos
    @users = User.all
    @students = Student.all
    @briefs = Brief.all
    @courses = Course.all
  end

  def depoimentos
    @users = User.all
    @students = Student.all
    @briefs = Brief.all
    @courses = Course.all
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dashboard_admin.html.erb
<%if user_signed_in?%>
    <%if current_user.admin?%>
    <br>
    <h3>Painel do Administrador</h3>
        <br>
        <h4>Usuários cadastrados no sistema</h4>
        <table class="table">
            <thead>
                <tr>
                <th>Email</th>
                <th>Perfil</th>
                </tr>
            </thead>

            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <td><%= user.email %></td>
                        <td><%= user.role %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    <%end%>
<%end%>

app/views/home/_dashboard_coordinator.html.erb
<%if user_signed_in?%>
  <%if current_user.coordinator?%>
    <br>
    <% @students.each do |s| %>
      <%if current_user.email == s.course.coordinator.email %>
        <%if s.pendente? %>
          <div class="message alert alert-warning alert-dismissible fade show" role="alert">
            Você tem <b>egressos</b> pendentes para aprovação
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <%end%>
        <%break%>
      <%end%>
    <%end%>  
    <% @briefs.each do |b| %>
      <%if current_user.email == b.student.course.coordinator.email %>
        <%if b.pendente? %>
          <div class="message alert alert-warning alert-dismissible fade show" role="alert">
            Você tem <b>depoimentos</b> pendentes para aprovação
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            </div>
          </div>
        <%end%>
        <%break%>
      <%end%>
    <%end%>

  
    <h3>Painel do Coordenador</h3>
    <br>
    <% @courses.each do |course| %>
        <% if current_user.email == course.coordinator.email%>
        <div class="panel panel-default">
        <div class="card">
        <div class="card-header">
        <%= course.coordinator.nome %>
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
          <p>
            <strong>Matrícula:</strong>
            <%= course.coordinator.matricula %>
            </p>

            <p>
            <strong>Email:</strong>
            <%= course.coordinator.email %>
            </p>

            <p>
            <strong>Curso:</strong>
            <%= course.nome %>
            </p>  
          </blockquote>
        </div>
      </div>
        <%end%>
    <%end%>
    <br><br>

    <h4>Egressos</h4>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Homologados</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Pendentes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Não homologados</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col">Ano</th>
            <th scope="col">Semestre</th>
            <th scope="col">Situação</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
            <% if current_user.email == student.course.coordinator.email && student.homologado? %>
              <tr>
                <td><%= student.nome %></td>
                <td><%= student.email %></td>
                <td><%= student.ano %></td>
                <td><%= student.semestre %></td>
                <td><%= student.homologado %></td>
              </tr>
            <%end%>
          <%end%>
        </tbody>
      </table>
      </div> 
      </div>
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col">Ano</th>
            <th scope="col">Semestre</th>
            <th scope="col">Situação</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
            <% if current_user.email == student.course.coordinator.email && student.pendente? %>
              <tr>
                <td><%= student.nome %></td>
                <td><%= student.email %></td>
                <td><%= student.ano %></td>
                <td><%= student.semestre %></td>
                <td><%= student.homologado %></td>
              </tr>
            <%end%>
          <%end%>
        </tbody>
      </table>
      </div> 
      </div>
      <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
      <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col">Ano</th>
            <th scope="col">Semestre</th>
            <th scope="col">Situação</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
            <% if current_user.email == student.course.coordinator.email && student.nao_homologado? %>
              <tr>
                <td><%= student.nome %></td>
                <td><%= student.email %></td>
                <td><%= student.ano %></td>
                <td><%= student.semestre %></td>
                <td><%= student.homologado %></td>
              </tr>
            <%end%>
          <%end%>
        </tbody>
      </table>
      </div> 
      </div>
    </div>
  <%end%>
<%end%>

app/views/home/_dashboard_public.html.erb
<div class="jumbotron" align="center">
    <h1 class="display-4">Egressos IFPB</h1>
    <p class="lead">Sistema para controle e visualização de egressos dos cursos do IFPB</p>
    <hr class="my-4">
    <p>Campus João Pessoa</p>
</div>

<div class ="row justify-content-around">
    <div class="col card border-primary mb-3" style="max-width: 18rem;">
        <div class="card-header">Banco de Talentos</div>
        <div class="card-body text-primary">
            <p class="card-text">Conheça os egressos dos cursos do IFPB.</p>
        </div>
        <%= link_to 'Clique aqui', home_talentos_path, :class => 'card-footer bg-transparent border-primary' %>
    </div>

    <div class="col card border-success mb-3" style="max-width: 18rem;">
        <div class="card-header">Depoimentos</div>
        <div class="card-body text-success">
            <p class="card-text">Saiba o que os egressos acharam dos cursos.</p>
        </div>
        <%= link_to 'Clique aqui', home_depoimentos_path, :class => 'card-footer bg-transparent border-success' %>
    </div>
</div>

<%if !user_signed_in?%>
    <footer class="footer">
        <div class="container">
        <br>
        <h4 class="text-muted">Realização</h4>
        <span class="text-muted">Curso Superior de Tecnologia em Sistemas para Internet</span>
        <h4 class="text-muted">Apoio</h4>
        <span class="text-muted">Instituto Federal de Educação, Tecnologia e Ciência da Paraíba</span>
        </div>
    </footer>
<%end%>

app/views/home/_dashboard_student.html.erb
<%if user_signed_in?%>
    <%if current_user.student?%>
        <br>
        <h2>Painel do Egresso</h2>
        <br>
        <% @students.each do |student| %>
            <% if current_user.email == student.email%>
            <div class="panel panel-default">
            <div class="card">
            <div class="card-header">
            <%= student.nome %>
            </div>
            <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>
                <strong>Matricula:</strong>
                <%= student.matricula %>
                </p>

                <p>
                <strong>Email:</strong>
                <%= student.email %>
                </p>

                <p>
                <strong>Curso:</strong>
                <%= student.course.nome %>
                </p>
            </blockquote>
            </div>
            </div>
            <%end%>
        <%end%>
        <br>
        <%= link_to 'Escrever depoimento sobre o curso', new_brief_path, :class => 'btn btn-success' %>
        
    <%end%>
<%end%>

app/views/home/depoimentos.html.erb
<h3>Depoimentos</h3>
<% @briefs.each do |b| %>
  <%if b.homologado?%>
    <%= b.texto %><br>
    <%= "#{b.student.nome}, formou-se em #{b.student.course.nome} em #{b.student.ano}/#{b.student.semestre}."%><br>
  <%end%>  
  <br><br>
<%end%>  

app/views/home/index.html.erb
<%= render partial: "home/dashboard_public" %>
<%= render partial: "home/dashboard_admin" %>
<%= render partial: "home/dashboard_student" %>
<%= render partial: "home/dashboard_coordinator" %>

app/views/home/talentos.html.erb
<h3>Banco de Talentos<h3>
<% @students.each do |s| %>
  <%if s.perfil == "publico" && s.homologado == "homologado"%>
  <br>
  <h4><%= s.nome %></h4>
  <h5>Curso: <%=s.course.nome %></h5>
    <% for contato in s.contacts %>
        <%= contato.tipo %>
        <%= contato.valor %><br>
    <% end %>  
  <%end%>  
<%end%>  