config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/talentos'
  get 'home/depoimentos'

  root 'home#index'

  resources :students
  resources :courses
  resources :briefs
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brief.rb
class Brief < ApplicationRecord
  belongs_to :student

  enum homologado: [:pendente, :homologado, :nao_homologado]
  
  validates :texto, presence: true
end

app/controllers/briefs_controller.rb
class BriefsController < ApplicationController
  before_action :set_brief, only: [:show, :edit, :update, :destroy]


  # GET /briefs
  # GET /briefs.json
  def index
    @briefs = Brief.all
  end

  # GET /briefs/1
  # GET /briefs/1.json
  def show
    @students = Student.all
  end

  # GET /briefs/new
  def new
    @brief = Brief.new
    @students = Student.all
  end

  # GET /briefs/1/edit
  def edit
    @students = Student.all
  end

  # POST /briefs
  # POST /briefs.json
  def create
    @brief = Brief.new(brief_params)

    respond_to do |format|
      if @brief.save
        format.html { redirect_to @brief, notice: 'Brief was successfully created.' }
        format.json { render :show, status: :created, location: @brief }
      else
        format.html { render :new }
        format.json { render json: @brief.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /briefs/1
  # PATCH/PUT /briefs/1.json
  def update
    respond_to do |format|
      if @brief.update(brief_params)
        format.html { redirect_to @brief, notice: 'Brief was successfully updated.' }
        format.json { render :show, status: :ok, location: @brief }
      else
        format.html { render :edit }
        format.json { render json: @brief.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /briefs/1
  # DELETE /briefs/1.json
  def destroy
    @brief.destroy
    respond_to do |format|
      format.html { redirect_to briefs_url, notice: 'Brief was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brief
      @brief = Brief.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brief_params
      params.require(:brief).permit(:texto, :data, :student_id, :homologado)
    end
end

app/helpers/briefs_helper.rb
module BriefsHelper
end

app/views/briefs/_form.html.erb
<%= form_with(model: brief, local: true) do |form| %>
  <% if brief.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brief.errors.count, "error") %> prohibited this brief from being saved:</h2>

      <ul>
      <% brief.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_area :texto, id: :brief_texto %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data, id: :brief_data %>
  </div>

  <%if user_signed_in?%>
    <%if current_user.student? %>
      <% @students.each do |s| %>
        <%if s.email == current_user.email %>
          <div style="visibility:hidden" class="field">
            <%= form.label :student_id %>
            <%= form.text_field :student_id, id: :brief_student_id, :value=>s.id %>
          </div>
        <%end%>
      <%end%>
    <%end%>
  <%end%>

  <% if user_signed_in? %>
    <% if current_user.coordinator?%>
      <div class="field">
        <%= form.label :homologado %>
        <%= form.select(:homologado, Brief.homologados.keys.map {|key| [key.humanize, key]},
          id: :brief_homologado) %>
      </div>
    <%end%>
  <%end%>

  <div class="actions">
    <%= form.submit 'Salvar', :class =>  "btn btn-success"   %>
  </div>
<% end %>

app/views/briefs/edit.html.erb
<h1>Editar Depoimento</h1>

<%= render 'form', brief: @brief %>

<br>
<%= link_to 'Exibir', @brief, :class =>  "btn btn-info"  %>
<%= link_to 'Voltar', briefs_path, :class =>  "btn btn-secondary"  %>

app/views/briefs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Depoimentos</h1>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Depoimento</th>
        <th scope="col">Data</th>
        <th scope="col">Autor</th>
        <th scope="col">Curso</th>
        <th scope="col">Situação</th>
        <th scope="col"></th>
        <th scope="col">Ações</th>
        <th scope="col"></th>
      </tr>
    </thead>

    <tbody>
      <% @briefs.each do |brief| %>
        <% if current_user.email == brief.student.email || brief.student.course.coordinator.email == current_user.email%>
          <tr>
            <td><%= brief.texto %></td>
            <td><%= brief.data %></td>
            <td><%= brief.student.nome %></td>
            <td><%= brief.student.course.sigla %></td>
            <td><%= brief.homologado %></td>
            <td><%= link_to 'Exibir', brief %></td>
            <td><%= link_to 'Alterar', edit_brief_path(brief) %></td>
            <% if current_user.coordinator? %>
              <td><%= link_to 'Apagar', brief, method: :delete, data: { confirm: 'Tem certeza que deseja apagar?' } %></td>
            <%end%>
          </tr>
        <%end%>
      <% end %>
    </tbody>
  </table>
</div>

app/views/briefs/new.html.erb
<h1>Criar Depoimento</h1>

<%= render 'form', brief: @brief %>
<br>
<%= link_to 'Voltar', briefs_path, :class =>  "btn btn-secondary"  %>

app/views/briefs/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Depoimento de <%= @brief.student.nome %>, matricula <%= @brief.student.matricula %></h3>

<p>
  <strong>Texto:</strong>
  <%= @brief.texto %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @brief.student.course.nome %>
</p>

<p>
  <strong>Data:</strong>
  <%= "#{@brief.data.day}/#{@brief.data.month}/#{@brief.data.year}" %>
</p>

<br>
<%= link_to 'Editar', edit_brief_path(@brief), :class =>  "btn btn-warning"  %>
<%= link_to 'Voltar', briefs_path, :class =>  "btn btn-secondary"   %>