config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/talentos'
  get 'home/depoimentos'

  root 'home#index'

  resources :students
  resources :courses
  resources :briefs
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg  navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">

    <ul class="navbar-nav">

      <%if user_signed_in?%>
          <%if current_user.admin? %>
            <li class="nav-item active">
              <a class="nav-item nav-link active" href="<%= courses_path %>">Cursos <span class="sr-only">(current)</span></a>   
            </li>
          <%elsif current_user.coordinator? %>
            <li class="nav-item">
              <a class="nav-item nav-link active" href="<%= students_path %>">Egressos</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link active" href="<%= briefs_path %>">Depoimentos</a>
            </li>
          <%elsif current_user.student? || current_user.normal_user? %>
            <li class="nav-item">
              <a class="nav-item nav-link active" href="<%= students_path %>">Perfil</a>
            </li>
          <%end%>
   
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%=current_user.email%>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Sair", destroy_user_session_path, method: :delete %>
            </div>
          </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-item nav-link" href="<%= new_user_session_path %>">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link" href="<%= new_student_path %>">Cadastrar</a>
        </li>
      <% end %>
    
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Egresso</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'home' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Roboto' %>
  </head>

  <body>
  	<%= render partial: "layouts/menu" %>
    <%= yield %>
  </body>
</html>